# Generated by Django 5.0.4 on 2024-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('level', models.CharField(choices=[('HARD', 'Продвинутый'), ('MEDIUM', 'Средний'), ('EASY', 'Для начинающих')], verbose_name='Уровень сложности')),
                ('duration', models.DurationField(verbose_name='Продолжительность выполнения')),
                ('repetitions', models.CharField(max_length=255, verbose_name='Рекомендуемый набор повторений и подходов')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
    ]
